server:
    port:  8090

test: hola 

repository:
    folder: \Users\David\Desktop\Trabajo\Haufe\filerepository
    maxSize: 100

logging:
    level: INFO

endpoints:
    health:
       sensitive: false
       enabled: yes
    shutdown:
       enabled: yes
       sensitive: false
       
       